name: Build, Test, and Upload Python Package

on:
  push:
    tags:
      - "v*.*.*"
      
  workflow_dispatch:

permissions:
  contents: read

jobs:
  # test:
  #      uses: ./.github/workflows/ubuntu-python-package.yml  # use the callable tests job to run tests

  deploy:
    name: Publish to PyPI
    container:
      image: node:22-bookworm

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        apt update
        apt install -y python3 python3-venv
        python -m pip install --upgrade pip

    - name: Publish to PyPI
      run: |
        python -m venv venv
        . ./venv/bin/activate
        pip install -U twine build
        python -m build .
        python -m twine upload --repository pypi --username __token__ --password ${{ secrets.PYPI }} dist/* 
      env:
        PYPI: ${{ secrets.PYPI }}
