name: Ubuntu Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install system and Python dependencies
      run: |
        sudo apt-get update
        sudo apt-get -qq install python3-pyqt5 xvfb libgl1 xvfb libxkbcommon-dev libegl1 fontconfig libxcb-cursor0
        python -m pip install --upgrade pip
        pip install pytest

    - name: Install test module and dependencies
      run: |
        pip install nqrduck-module

    - name: Run all the tests
      run: xvfb-run pytest tests/
